//name : main_0
//output : output_value:16
//source_file : /tmp/tmpqm0Sya/inline_c_file.c

///+============================================================================+
///|                                                                            |
///|                     This file was generated by Chips                       |
///|                                                                            |
///|                                  Chips                                     |
///|                                                                            |
///|                      http://github.com/dawsonjon/Chips-2.0                 |
///|                                                                            |
///|                                                             Python powered |
///+============================================================================+
module main_0(output_value_ack,clk,rst,output_value,output_value_stb,exception);
  integer file_count;
  parameter  stop = 3'd0,
  instruction_fetch = 3'd1,
  operand_fetch = 3'd2,
  execute = 3'd3,
  load = 3'd4,
  wait_state = 3'd5,
  read = 3'd6,
  write = 3'd7;
  input output_value_ack;
  input clk;
  input rst;
  output [31:0] output_value;
  output output_value_stb;
  reg [31:0] timer;
  reg [63:0] timer_clock;
  reg [15:0] program_counter;
  reg [15:0] program_counter_1;
  reg [15:0] program_counter_2;
  reg [43:0] instruction;
  reg [3:0] opcode_2;
  reg [3:0] a;
  reg [3:0] b;
  reg [3:0] z;
  reg write_enable;
  reg [3:0] address_a_2;
  reg [3:0] address_b_2;
  reg [3:0] address_z_2;
  reg [3:0] address_z_3;
  reg [31:0] load_data;
  reg [31:0] write_output;
  reg [31:0] write_value;
  reg [31:0] read_input;
  reg [15:0] literal_2;
  reg [31:0] a_hi;
  reg [31:0] b_hi;
  reg [31:0] a_lo;
  reg [31:0] b_lo;
  reg [63:0] long_result;
  reg [31:0] result;
  reg [15:0] address;
  reg [31:0] data_out;
  reg [31:0] data_in;
  reg [31:0] carry;
  reg [31:0] s_output_value_stb;
  reg [31:0] s_output_value;
  reg [7:0] state;
  output reg exception;
  reg [27:0] instructions [54:0];
  reg [31:0] memory [4096:0];
  reg [31:0] registers [15:0];
  wire [31:0] operand_a;
  wire [31:0] operand_b;
  wire [31:0] register_a;
  wire [31:0] register_b;
  wire [15:0] literal;
  wire [3:0] opcode;
  wire [3:0] address_a;
  wire [3:0] address_b;
  wire [3:0] address_z;
  wire [15:0] load_address;
  wire [15:0] store_address;
  wire [31:0] store_data;
  wire  store_enable;

  //////////////////////////////////////////////////////////////////////////////
  // INSTRUCTION INITIALIZATION                                                 
  //                                                                            
  // Initialise the contents of the instruction memory                          
  //
  // Intruction Set
  // ==============
  // 0 {'literal': True, 'op': 'literal'}
  // 1 {'literal': True, 'op': 'addl'}
  // 2 {'literal': False, 'op': 'store'}
  // 3 {'literal': True, 'op': 'call'}
  // 4 {'literal': False, 'op': 'stop'}
  // 5 {'literal': False, 'op': 'load'}
  // 6 {'literal': False, 'op': 'add'}
  // 7 {'literal': True, 'op': 'literal_hi'}
  // 8 {'literal': False, 'op': 'and'}
  // 9 {'literal': False, 'op': 'write'}
  // 10 {'literal': False, 'op': 'wait_clocks'}
  // 11 {'literal': True, 'op': 'goto'}
  // 12 {'literal': False, 'op': 'return'}
  // Intructions
  // ===========
  
  initial
  begin
    instructions[0] = {4'd0, 4'd3, 4'd0, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 9 {'literal': 0, 'z': 3, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 9, 'op': 'literal'}
    instructions[1] = {4'd0, 4'd4, 4'd0, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 9 {'literal': 0, 'z': 4, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 9, 'op': 'literal'}
    instructions[2] = {4'd1, 4'd3, 4'd3, 16'd1};///tmp/tmpqm0Sya/inline_c_file.c : 9 {'a': 3, 'literal': 1, 'z': 3, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 9, 'op': 'addl'}
    instructions[3] = {4'd0, 4'd8, 4'd0, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 1 {'literal': 0, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 1, 'op': 'literal'}
    instructions[4] = {4'd0, 4'd2, 4'd0, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 1 {'literal': 0, 'z': 2, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 1, 'op': 'literal'}
    instructions[5] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpqm0Sya/inline_c_file.c : 1 {'a': 2, 'b': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 1, 'op': 'store'}
    instructions[6] = {4'd1, 4'd7, 4'd4, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 9 {'a': 4, 'literal': 0, 'z': 7, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 9, 'op': 'addl'}
    instructions[7] = {4'd1, 4'd4, 4'd3, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 9 {'a': 3, 'literal': 0, 'z': 4, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 9, 'op': 'addl'}
    instructions[8] = {4'd3, 4'd6, 4'd0, 16'd10};///tmp/tmpqm0Sya/inline_c_file.c : 9 {'z': 6, 'label': 10, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 9, 'op': 'call'}
    instructions[9] = {4'd4, 4'd0, 4'd0, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 9 {'trace': /tmp/tmpqm0Sya/inline_c_file.c : 9, 'op': 'stop'}
    instructions[10] = {4'd1, 4'd3, 4'd3, 16'd1};///tmp/tmpqm0Sya/inline_c_file.c : 2 {'a': 3, 'literal': 1, 'z': 3, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 2, 'op': 'addl'}
    instructions[11] = {4'd0, 4'd8, 4'd0, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 3 {'literal': 0, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 3, 'op': 'literal'}
    instructions[12] = {4'd1, 4'd2, 4'd4, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 3 {'a': 4, 'literal': 0, 'z': 2, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 3, 'op': 'addl'}
    instructions[13] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpqm0Sya/inline_c_file.c : 3 {'a': 2, 'b': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 3, 'op': 'store'}
    instructions[14] = {4'd0, 4'd8, 4'd0, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'literal': 0, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'literal'}
    instructions[15] = {4'd1, 4'd2, 4'd8, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 8, 'literal': 0, 'z': 2, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'addl'}
    instructions[16] = {4'd5, 4'd8, 4'd2, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 2, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'load'}
    instructions[17] = {4'd2, 4'd0, 4'd3, 16'd8};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'store'}
    instructions[18] = {4'd1, 4'd3, 4'd3, 16'd1};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'literal': 1, 'z': 3, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'addl'}
    instructions[19] = {4'd1, 4'd8, 4'd4, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 4, 'literal': 0, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'addl'}
    instructions[20] = {4'd1, 4'd2, 4'd8, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 8, 'literal': 0, 'z': 2, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'addl'}
    instructions[21] = {4'd5, 4'd8, 4'd2, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 2, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'load'}
    instructions[22] = {4'd2, 4'd0, 4'd3, 16'd8};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'store'}
    instructions[23] = {4'd1, 4'd3, 4'd3, 16'd1};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'literal': 1, 'z': 3, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'addl'}
    instructions[24] = {4'd0, 4'd8, 4'd0, 16'd1};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'literal': 1, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'literal'}
    instructions[25] = {4'd2, 4'd0, 4'd3, 16'd8};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'store'}
    instructions[26] = {4'd1, 4'd3, 4'd3, 16'd1};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'literal': 1, 'z': 3, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'addl'}
    instructions[27] = {4'd1, 4'd8, 4'd4, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 4, 'literal': 0, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'addl'}
    instructions[28] = {4'd1, 4'd2, 4'd8, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 8, 'literal': 0, 'z': 2, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'addl'}
    instructions[29] = {4'd5, 4'd8, 4'd2, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 2, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'load'}
    instructions[30] = {4'd1, 4'd3, 4'd3, -16'd1};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'comment': 'pop', 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[31] = {4'd5, 4'd10, 4'd3, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'z': 10, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'load'}
    instructions[32] = {4'd6, 4'd8, 4'd8, 16'd10};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 8, 'z': 8, 'b': 10, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'add'}
    instructions[33] = {4'd1, 4'd2, 4'd4, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 4, 'literal': 0, 'z': 2, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'addl'}
    instructions[34] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 2, 'b': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'store'}
    instructions[35] = {4'd1, 4'd3, 4'd3, -16'd1};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'comment': 'pop', 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[36] = {4'd5, 4'd8, 4'd3, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'load'}
    instructions[37] = {4'd2, 4'd0, 4'd3, 16'd8};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'store'}
    instructions[38] = {4'd1, 4'd3, 4'd3, 16'd1};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'literal': 1, 'z': 3, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'addl'}
    instructions[39] = {4'd0, 4'd8, 4'd0, 16'd65535};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'literal': 65535, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'literal'}
    instructions[40] = {4'd7, 4'd8, 4'd8, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 8, 'literal': 0, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'literal_hi'}
    instructions[41] = {4'd1, 4'd3, 4'd3, -16'd1};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'comment': 'pop', 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[42] = {4'd5, 4'd10, 4'd3, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'z': 10, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'load'}
    instructions[43] = {4'd8, 4'd8, 4'd8, 16'd10};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 8, 'z': 8, 'b': 10, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'and'}
    instructions[44] = {4'd1, 4'd3, 4'd3, -16'd1};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'comment': 'pop', 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[45] = {4'd5, 4'd0, 4'd3, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'z': 0, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'load'}
    instructions[46] = {4'd9, 4'd0, 4'd0, 16'd8};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 0, 'b': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'write'}
    instructions[47] = {4'd1, 4'd3, 4'd3, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 5 {'a': 3, 'literal': 0, 'z': 3, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 5, 'op': 'addl'}
    instructions[48] = {4'd0, 4'd8, 4'd0, 16'd61568};///tmp/tmpqm0Sya/inline_c_file.c : 6 {'literal': 61568, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 6, 'op': 'literal'}
    instructions[49] = {4'd7, 4'd8, 4'd8, 16'd762};///tmp/tmpqm0Sya/inline_c_file.c : 6 {'a': 8, 'literal': 762, 'z': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 6, 'op': 'literal_hi'}
    instructions[50] = {4'd10, 4'd0, 4'd8, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 6 {'a': 8, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 6, 'op': 'wait_clocks'}
    instructions[51] = {4'd11, 4'd0, 4'd0, 16'd14};///tmp/tmpqm0Sya/inline_c_file.c : 4 {'label': 14, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 4, 'op': 'goto'}
    instructions[52] = {4'd1, 4'd3, 4'd4, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 2 {'a': 4, 'literal': 0, 'z': 3, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 2, 'op': 'addl'}
    instructions[53] = {4'd1, 4'd4, 4'd7, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 2 {'a': 7, 'literal': 0, 'z': 4, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 2, 'op': 'addl'}
    instructions[54] = {4'd12, 4'd0, 4'd6, 16'd0};///tmp/tmpqm0Sya/inline_c_file.c : 2 {'a': 6, 'trace': /tmp/tmpqm0Sya/inline_c_file.c : 2, 'op': 'return'}
  end

  
  always @(posedge clk)
  begin
    load_data <= memory[load_address];
    if(store_enable && state == execute) begin
      memory[store_address] <= store_data;
    end
  end


  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 1 -- FETCH INSTRUCTION
  //                                                                            
  
  always @(posedge clk)
  begin
    //implement memory for instructions
    if (state == instruction_fetch || state == operand_fetch || state == execute) begin
      instruction <= instructions[program_counter];
      program_counter_1 <= program_counter;
    end
  end

  assign opcode    = instruction[27:24];
  assign address_z = instruction[23:20];
  assign address_a = instruction[19:16];
  assign address_b = instruction[3:0];
  assign literal   = instruction[15:0];

  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 2 -- FETCH OPERANDS
  //                                                                            
  
  always @(posedge clk)
  begin
    if (write_enable) begin
      registers[address_z_3] <= result;
    end
    if (state == operand_fetch || state == execute) begin
      opcode_2 <= opcode;
      literal_2 <= literal;
      address_a_2 <= address_a;
      address_b_2 <= address_b;
      address_z_2 <= address_z;
      program_counter_2 <= program_counter_1;
    end
  end
  assign register_a = registers[address_a_2];
  assign register_b = registers[address_b_2];
  assign operand_a = (address_a_2 == address_z_3 && write_enable)?result:register_a;
  assign operand_b = (address_b_2 == address_z_3 && write_enable)?result:register_b;
  assign store_address = operand_a;
  assign load_address = operand_a;
  assign store_data = operand_b;
  assign store_enable = (opcode_2==2);

  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 3 -- EXECUTE
  //                                                                            
  
  always @(posedge clk)
  begin

  write_enable <= 0;
  timer_clock <= timer_clock + 1;
  case(state)

    //instruction_fetch
    instruction_fetch: begin
      program_counter <= program_counter + 1;
      state <= operand_fetch;
    end
    //operand_fetch
    operand_fetch: begin
      program_counter <= program_counter + 1;
      state <= execute;
    end
    //execute
    execute: begin
      program_counter <= program_counter + 1;
      address_z_3 <= address_z_2;
      case(opcode_2)

        //literal
        16'd0:
        begin
          result<=$signed(literal_2);
          write_enable <= 1;
        end

        //addl
        16'd1:
        begin
          result<=operand_a + literal_2;
          write_enable <= 1;
        end

        //store
        16'd2:
        begin
        end

        //call
        16'd3:
        begin
          result <= program_counter_2 + 1;
          write_enable <= 1;
          program_counter <= literal_2;
          state <= instruction_fetch;
        end

        //stop
        16'd4:
        begin
        state <= stop;
        end

        //load
        16'd5:
        begin
          state <= load;
        end

        //add
        16'd6:
        begin
          long_result = operand_a + operand_b;
          result <= long_result[31:0];
          carry[0] <= long_result[32];
          write_enable <= 1;
        end

        //literal_hi
        16'd7:
        begin
          result<= {literal_2, operand_a[15:0]};
          write_enable <= 1;
        end

        //and
        16'd8:
        begin
          result <= operand_a & operand_b;
          write_enable <= 1;
        end

        //write
        16'd9:
        begin
          state <= write;
          write_output <= operand_a;
          write_value <= operand_b;
        end

        //wait_clocks
        16'd10:
        begin
          timer <= operand_a;
          state <= wait_state;
        end

        //goto
        16'd11:
        begin
          program_counter <= literal_2;
          state <= instruction_fetch;
        end

        //return
        16'd12:
        begin
          program_counter <= operand_a;
          state <= instruction_fetch;
        end

      endcase

    end

    write:
    begin
      case(write_output)
      0:
      begin
        s_output_value_stb <= 1;
        s_output_value <= write_value;
        if (output_value_ack && s_output_value_stb) begin
          s_output_value_stb <= 0;
          state <= execute;
        end
      end
      endcase
    end

    load:
    begin
        result <= load_data;
        write_enable <= 1;
        state <= execute;
    end

    wait_state:
    begin
      if (timer) begin
        timer <= timer - 1;
      end else begin
        state <= execute;
      end
    end

    stop:
    begin
    end

    endcase

    if (rst == 1'b1) begin
      timer <= 0;
      timer_clock <= 0;
      program_counter <= 0;
      address_z_3 <= 0;
      result <= 0;
      a = 0;
      b = 0;
      z = 0;
      state <= instruction_fetch;
      s_output_value_stb <= 0;
    end
  end
  assign output_value_stb = s_output_value_stb;
  assign output_value = s_output_value;

endmodule
