# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-4903-jon-GA-MA770T-ES3/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_12.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_11.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_13.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_10.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_0.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_1.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_2.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_3.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_4.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_5.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_6.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_7.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_8.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/main_9.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/user_design.v
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/chips_lib.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/serial_out.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/serial_in.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/rmii_ethernet.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/i2c.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/pwm.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/keyboard.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/bram.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/svga_package.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/svga_core.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/svga_timing_gen.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/pwm_audio.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/interpolate.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/nco.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/serdes.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/dac_interface.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/transmitter.vhd
      /home/storage/Projects/FPGA-TX/synthesis/nexys_4/tx/bsp.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-4903-jon-GA-MA770T-ES3/realtime/bsp_synth.xdc
    rt::sdcChecksum
    set rt::top bsp
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {./.Xil/Vivado-4903-jon-GA-MA770T-ES3/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-4903-jon-GA-MA770T-ES3/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
      rt::run_synthesis -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
