//name : main_0
//output : output_rs232_tx:16
//source_file : /tmp/tmpEtvNgA/inline_c_file.c

///+============================================================================+
///|                                                                            |
///|                     This file was generated by Chips                       |
///|                                                                            |
///|                                  Chips                                     |
///|                                                                            |
///|                      http://github.com/dawsonjon/Chips-2.0                 |
///|                                                                            |
///|                                                             Python powered |
///+============================================================================+
module main_0(output_rs232_tx_ack,clk,rst,output_rs232_tx,output_rs232_tx_stb,exception);
  integer file_count;
  parameter  stop = 3'd0,
  instruction_fetch = 3'd1,
  operand_fetch = 3'd2,
  execute = 3'd3,
  load = 3'd4,
  wait_state = 3'd5,
  read = 3'd6,
  write = 3'd7;
  input output_rs232_tx_ack;
  input clk;
  input rst;
  output [31:0] output_rs232_tx;
  output output_rs232_tx_stb;
  reg [31:0] timer;
  reg [63:0] timer_clock;
  reg [15:0] program_counter;
  reg [15:0] program_counter_1;
  reg [15:0] program_counter_2;
  reg [43:0] instruction;
  reg [3:0] opcode_2;
  reg [3:0] a;
  reg [3:0] b;
  reg [3:0] z;
  reg write_enable;
  reg [3:0] address_a_2;
  reg [3:0] address_b_2;
  reg [3:0] address_z_2;
  reg [3:0] address_z_3;
  reg [31:0] load_data;
  reg [31:0] write_output;
  reg [31:0] write_value;
  reg [31:0] read_input;
  reg [15:0] literal_2;
  reg [31:0] a_hi;
  reg [31:0] b_hi;
  reg [31:0] a_lo;
  reg [31:0] b_lo;
  reg [63:0] long_result;
  reg [31:0] result;
  reg [15:0] address;
  reg [31:0] data_out;
  reg [31:0] data_in;
  reg [31:0] carry;
  reg [31:0] s_output_rs232_tx_stb;
  reg [31:0] s_output_rs232_tx;
  reg [7:0] state;
  output reg exception;
  reg [27:0] instructions [165:0];
  reg [31:0] memory [4096:0];
  reg [31:0] registers [15:0];
  wire [31:0] operand_a;
  wire [31:0] operand_b;
  wire [31:0] register_a;
  wire [31:0] register_b;
  wire [15:0] literal;
  wire [3:0] opcode;
  wire [3:0] address_a;
  wire [3:0] address_b;
  wire [3:0] address_z;
  wire [15:0] load_address;
  wire [15:0] store_address;
  wire [31:0] store_data;
  wire  store_enable;

  //////////////////////////////////////////////////////////////////////////////
  // INSTRUCTION INITIALIZATION                                                 
  //                                                                            
  // Initialise the contents of the instruction memory                          
  //
  // Intruction Set
  // ==============
  // 0 {'literal': True, 'op': 'literal'}
  // 1 {'literal': True, 'op': 'addl'}
  // 2 {'literal': False, 'op': 'store'}
  // 3 {'literal': True, 'op': 'call'}
  // 4 {'literal': False, 'op': 'stop'}
  // 5 {'literal': False, 'op': 'load'}
  // 6 {'literal': False, 'op': 'return'}
  // 7 {'literal': False, 'op': 'add'}
  // 8 {'literal': True, 'op': 'jmp_if_false'}
  // 9 {'literal': False, 'op': 'write'}
  // 10 {'literal': True, 'op': 'goto'}
  // Intructions
  // ===========
  
  initial
  begin
    instructions[0] = {4'd0, 4'd3, 4'd0, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 8 {'literal': 0, 'z': 3, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 8, 'op': 'literal'}
    instructions[1] = {4'd0, 4'd4, 4'd0, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 8 {'literal': 0, 'z': 4, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 8, 'op': 'literal'}
    instructions[2] = {4'd1, 4'd3, 4'd3, 16'd16};///tmp/tmpEtvNgA/inline_c_file.c : 8 {'a': 3, 'literal': 16, 'z': 3, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 8, 'op': 'addl'}
    instructions[3] = {4'd0, 4'd8, 4'd0, 16'd72};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 72, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[4] = {4'd0, 4'd2, 4'd0, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 0, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[5] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[6] = {4'd0, 4'd8, 4'd0, 16'd101};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 101, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[7] = {4'd0, 4'd2, 4'd0, 16'd1};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 1, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[8] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[9] = {4'd0, 4'd8, 4'd0, 16'd108};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 108, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[10] = {4'd0, 4'd2, 4'd0, 16'd2};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 2, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[11] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[12] = {4'd0, 4'd8, 4'd0, 16'd108};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 108, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[13] = {4'd0, 4'd2, 4'd0, 16'd3};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 3, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[14] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[15] = {4'd0, 4'd8, 4'd0, 16'd111};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 111, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[16] = {4'd0, 4'd2, 4'd0, 16'd4};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 4, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[17] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[18] = {4'd0, 4'd8, 4'd0, 16'd32};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 32, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[19] = {4'd0, 4'd2, 4'd0, 16'd5};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 5, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[20] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[21] = {4'd0, 4'd8, 4'd0, 16'd87};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 87, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[22] = {4'd0, 4'd2, 4'd0, 16'd6};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 6, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[23] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[24] = {4'd0, 4'd8, 4'd0, 16'd111};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 111, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[25] = {4'd0, 4'd2, 4'd0, 16'd7};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 7, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[26] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[27] = {4'd0, 4'd8, 4'd0, 16'd114};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 114, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[28] = {4'd0, 4'd2, 4'd0, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 8, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[29] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[30] = {4'd0, 4'd8, 4'd0, 16'd108};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 108, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[31] = {4'd0, 4'd2, 4'd0, 16'd9};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 9, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[32] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[33] = {4'd0, 4'd8, 4'd0, 16'd100};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 100, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[34] = {4'd0, 4'd2, 4'd0, 16'd10};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 10, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[35] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[36] = {4'd0, 4'd8, 4'd0, 16'd33};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 33, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[37] = {4'd0, 4'd2, 4'd0, 16'd11};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 11, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[38] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[39] = {4'd0, 4'd8, 4'd0, 16'd10};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 10, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[40] = {4'd0, 4'd2, 4'd0, 16'd12};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 12, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[41] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[42] = {4'd0, 4'd8, 4'd0, 16'd32};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 32, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[43] = {4'd0, 4'd2, 4'd0, 16'd13};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 13, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[44] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[45] = {4'd0, 4'd8, 4'd0, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 0, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[46] = {4'd0, 4'd2, 4'd0, 16'd14};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 14, 'z': 2, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[47] = {4'd2, 4'd0, 4'd2, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'a': 2, 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'store'}
    instructions[48] = {4'd0, 4'd8, 4'd0, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 5 {'literal': 0, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 5, 'op': 'literal'}
    instructions[49] = {4'd0, 4'd2, 4'd0, 16'd15};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 5 {'literal': 15, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 5, 'op': 'literal'}
    instructions[50] = {4'd2, 4'd0, 4'd2, 16'd8};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 5 {'a': 2, 'b': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 5, 'op': 'store'}
    instructions[51] = {4'd1, 4'd7, 4'd4, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 8 {'a': 4, 'literal': 0, 'z': 7, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 8, 'op': 'addl'}
    instructions[52] = {4'd1, 4'd4, 4'd3, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 8 {'a': 3, 'literal': 0, 'z': 4, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 8, 'op': 'addl'}
    instructions[53] = {4'd3, 4'd6, 4'd0, 16'd55};///tmp/tmpEtvNgA/inline_c_file.c : 8 {'z': 6, 'label': 55, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 8, 'op': 'call'}
    instructions[54] = {4'd4, 4'd0, 4'd0, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 8 {'trace': /tmp/tmpEtvNgA/inline_c_file.c : 8, 'op': 'stop'}
    instructions[55] = {4'd1, 4'd3, 4'd3, 16'd15};///tmp/tmpEtvNgA/inline_c_file.c : 4 {'a': 3, 'literal': 15, 'z': 3, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 4, 'op': 'addl'}
    instructions[56] = {4'd2, 4'd0, 4'd3, 16'd6};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 3, 'comment': 'push', 'b': 6, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'op': 'store'}
    instructions[57] = {4'd1, 4'd3, 4'd3, 16'd1};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 3, 'literal': 1, 'z': 3, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'op': 'addl'}
    instructions[58] = {4'd2, 4'd0, 4'd3, 16'd7};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 3, 'comment': 'push', 'b': 7, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'op': 'store'}
    instructions[59] = {4'd1, 4'd3, 4'd3, 16'd1};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 3, 'literal': 1, 'z': 3, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'op': 'addl'}
    instructions[60] = {4'd0, 4'd8, 4'd0, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 6 {'literal': 0, 'z': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 6, 'op': 'literal'}
    instructions[61] = {4'd2, 4'd0, 4'd3, 16'd8};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'op': 'store'}
    instructions[62] = {4'd1, 4'd3, 4'd3, 16'd1};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 3, 'literal': 1, 'z': 3, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'op': 'addl'}
    instructions[63] = {4'd1, 4'd7, 4'd4, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 4, 'literal': 0, 'z': 7, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'op': 'addl'}
    instructions[64] = {4'd1, 4'd4, 4'd3, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 3, 'literal': 0, 'z': 4, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'op': 'addl'}
    instructions[65] = {4'd3, 4'd6, 4'd0, 16'd75};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'z': 6, 'label': 75, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'op': 'call'}
    instructions[66] = {4'd1, 4'd3, 4'd3, -16'd1};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 3, 'literal': -1, 'z': 3, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'op': 'addl'}
    instructions[67] = {4'd1, 4'd3, 4'd3, -16'd1};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 3, 'comment': 'pop', 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[68] = {4'd5, 4'd7, 4'd3, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 3, 'z': 7, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'op': 'load'}
    instructions[69] = {4'd1, 4'd3, 4'd3, -16'd1};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 3, 'comment': 'pop', 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[70] = {4'd5, 4'd6, 4'd3, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 3, 'z': 6, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'op': 'load'}
    instructions[71] = {4'd1, 4'd3, 4'd3, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 5 {'a': 3, 'literal': 0, 'z': 3, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 5, 'op': 'addl'}
    instructions[72] = {4'd1, 4'd3, 4'd4, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 4 {'a': 4, 'literal': 0, 'z': 3, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 4, 'op': 'addl'}
    instructions[73] = {4'd1, 4'd4, 4'd7, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 4 {'a': 7, 'literal': 0, 'z': 4, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 4, 'op': 'addl'}
    instructions[74] = {4'd6, 4'd0, 4'd6, 16'd0};///tmp/tmpEtvNgA/inline_c_file.c : 4 {'a': 6, 'trace': /tmp/tmpEtvNgA/inline_c_file.c : 4, 'op': 'return'}
    instructions[75] = {4'd1, 4'd3, 4'd3, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 73 {'a': 3, 'literal': 0, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 73, 'op': 'addl'}
    instructions[76] = {4'd2, 4'd0, 4'd3, 16'd6};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'comment': 'push', 'b': 6, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'store'}
    instructions[77] = {4'd1, 4'd3, 4'd3, 16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'literal': 1, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'addl'}
    instructions[78] = {4'd2, 4'd0, 4'd3, 16'd7};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'comment': 'push', 'b': 7, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'store'}
    instructions[79] = {4'd1, 4'd3, 4'd3, 16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'literal': 1, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'addl'}
    instructions[80] = {4'd1, 4'd8, 4'd4, -16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 4, 'literal': -1, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'addl'}
    instructions[81] = {4'd1, 4'd2, 4'd8, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 8, 'literal': 0, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'addl'}
    instructions[82] = {4'd5, 4'd8, 4'd2, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 2, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'load'}
    instructions[83] = {4'd2, 4'd0, 4'd3, 16'd8};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'store'}
    instructions[84] = {4'd1, 4'd3, 4'd3, 16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'literal': 1, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'addl'}
    instructions[85] = {4'd0, 4'd8, 4'd0, 16'd15};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'literal': 15, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'literal'}
    instructions[86] = {4'd1, 4'd2, 4'd8, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 8, 'literal': 0, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'addl'}
    instructions[87] = {4'd5, 4'd8, 4'd2, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 2, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'load'}
    instructions[88] = {4'd2, 4'd0, 4'd3, 16'd8};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'store'}
    instructions[89] = {4'd1, 4'd3, 4'd3, 16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'literal': 1, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'addl'}
    instructions[90] = {4'd1, 4'd7, 4'd4, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 4, 'literal': 0, 'z': 7, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'addl'}
    instructions[91] = {4'd1, 4'd4, 4'd3, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'literal': 0, 'z': 4, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'addl'}
    instructions[92] = {4'd3, 4'd6, 4'd0, 16'd102};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'z': 6, 'label': 102, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'call'}
    instructions[93] = {4'd1, 4'd3, 4'd3, -16'd2};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'literal': -2, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'addl'}
    instructions[94] = {4'd1, 4'd3, 4'd3, -16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'comment': 'pop', 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[95] = {4'd5, 4'd7, 4'd3, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'z': 7, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'load'}
    instructions[96] = {4'd1, 4'd3, 4'd3, -16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'comment': 'pop', 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[97] = {4'd5, 4'd6, 4'd3, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'z': 6, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'load'}
    instructions[98] = {4'd1, 4'd3, 4'd3, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74 {'a': 3, 'literal': 0, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 74, 'op': 'addl'}
    instructions[99] = {4'd1, 4'd3, 4'd4, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 73 {'a': 4, 'literal': 0, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 73, 'op': 'addl'}
    instructions[100] = {4'd1, 4'd4, 4'd7, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 73 {'a': 7, 'literal': 0, 'z': 4, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 73, 'op': 'addl'}
    instructions[101] = {4'd6, 4'd0, 4'd6, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 73 {'a': 6, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 73, 'op': 'return'}
    instructions[102] = {4'd1, 4'd3, 4'd3, 16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 23 {'a': 3, 'literal': 1, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 23, 'op': 'addl'}
    instructions[103] = {4'd0, 4'd8, 4'd0, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 24 {'literal': 0, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 24, 'op': 'literal'}
    instructions[104] = {4'd1, 4'd2, 4'd4, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 24 {'a': 4, 'literal': 0, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 24, 'op': 'addl'}
    instructions[105] = {4'd2, 4'd0, 4'd2, 16'd8};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 24 {'a': 2, 'b': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 24, 'op': 'store'}
    instructions[106] = {4'd1, 4'd8, 4'd4, -16'd2};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'a': 4, 'literal': -2, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'op': 'addl'}
    instructions[107] = {4'd1, 4'd2, 4'd8, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'a': 8, 'literal': 0, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'op': 'addl'}
    instructions[108] = {4'd5, 4'd8, 4'd2, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'a': 2, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'op': 'load'}
    instructions[109] = {4'd2, 4'd0, 4'd3, 16'd8};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'op': 'store'}
    instructions[110] = {4'd1, 4'd3, 4'd3, 16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'a': 3, 'literal': 1, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'op': 'addl'}
    instructions[111] = {4'd1, 4'd8, 4'd4, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'a': 4, 'literal': 0, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'op': 'addl'}
    instructions[112] = {4'd1, 4'd2, 4'd8, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'a': 8, 'literal': 0, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'op': 'addl'}
    instructions[113] = {4'd5, 4'd8, 4'd2, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'a': 2, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'op': 'load'}
    instructions[114] = {4'd1, 4'd3, 4'd3, -16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'a': 3, 'comment': 'pop', 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[115] = {4'd5, 4'd2, 4'd3, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'a': 3, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'op': 'load'}
    instructions[116] = {4'd7, 4'd8, 4'd8, 16'd2};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'a': 8, 'z': 8, 'b': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'op': 'add'}
    instructions[117] = {4'd1, 4'd2, 4'd8, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'a': 8, 'literal': 0, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'op': 'addl'}
    instructions[118] = {4'd5, 4'd8, 4'd2, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'a': 2, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'op': 'load'}
    instructions[119] = {4'd8, 4'd0, 4'd8, 16'd161};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 29 {'a': 8, 'label': 161, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 29, 'op': 'jmp_if_false'}
    instructions[120] = {4'd1, 4'd8, 4'd4, -16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 4, 'literal': -1, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'addl'}
    instructions[121] = {4'd1, 4'd2, 4'd8, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 8, 'literal': 0, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'addl'}
    instructions[122] = {4'd5, 4'd8, 4'd2, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 2, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'load'}
    instructions[123] = {4'd2, 4'd0, 4'd3, 16'd8};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'store'}
    instructions[124] = {4'd1, 4'd3, 4'd3, 16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 3, 'literal': 1, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'addl'}
    instructions[125] = {4'd1, 4'd8, 4'd4, -16'd2};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 4, 'literal': -2, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'addl'}
    instructions[126] = {4'd1, 4'd2, 4'd8, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 8, 'literal': 0, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'addl'}
    instructions[127] = {4'd5, 4'd8, 4'd2, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 2, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'load'}
    instructions[128] = {4'd2, 4'd0, 4'd3, 16'd8};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'store'}
    instructions[129] = {4'd1, 4'd3, 4'd3, 16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 3, 'literal': 1, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'addl'}
    instructions[130] = {4'd1, 4'd8, 4'd4, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 4, 'literal': 0, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'addl'}
    instructions[131] = {4'd1, 4'd2, 4'd8, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 8, 'literal': 0, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'addl'}
    instructions[132] = {4'd5, 4'd8, 4'd2, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 2, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'load'}
    instructions[133] = {4'd1, 4'd3, 4'd3, -16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 3, 'comment': 'pop', 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[134] = {4'd5, 4'd2, 4'd3, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 3, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'load'}
    instructions[135] = {4'd7, 4'd8, 4'd8, 16'd2};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 8, 'z': 8, 'b': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'add'}
    instructions[136] = {4'd1, 4'd2, 4'd8, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 8, 'literal': 0, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'addl'}
    instructions[137] = {4'd5, 4'd8, 4'd2, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 2, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'load'}
    instructions[138] = {4'd1, 4'd3, 4'd3, -16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 3, 'comment': 'pop', 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[139] = {4'd5, 4'd0, 4'd3, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 3, 'z': 0, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'load'}
    instructions[140] = {4'd9, 4'd0, 4'd0, 16'd8};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 0, 'b': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'write'}
    instructions[141] = {4'd1, 4'd3, 4'd3, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26 {'a': 3, 'literal': 0, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 26, 'op': 'addl'}
    instructions[142] = {4'd1, 4'd8, 4'd4, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 4, 'literal': 0, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'addl'}
    instructions[143] = {4'd1, 4'd2, 4'd8, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 8, 'literal': 0, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'addl'}
    instructions[144] = {4'd5, 4'd8, 4'd2, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 2, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'load'}
    instructions[145] = {4'd2, 4'd0, 4'd3, 16'd8};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'store'}
    instructions[146] = {4'd1, 4'd3, 4'd3, 16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 3, 'literal': 1, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'addl'}
    instructions[147] = {4'd0, 4'd8, 4'd0, 16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'literal': 1, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'literal'}
    instructions[148] = {4'd2, 4'd0, 4'd3, 16'd8};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 3, 'comment': 'push', 'b': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'store'}
    instructions[149] = {4'd1, 4'd3, 4'd3, 16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 3, 'literal': 1, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'addl'}
    instructions[150] = {4'd1, 4'd8, 4'd4, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 4, 'literal': 0, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'addl'}
    instructions[151] = {4'd1, 4'd2, 4'd8, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 8, 'literal': 0, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'addl'}
    instructions[152] = {4'd5, 4'd8, 4'd2, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 2, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'load'}
    instructions[153] = {4'd1, 4'd3, 4'd3, -16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 3, 'comment': 'pop', 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[154] = {4'd5, 4'd10, 4'd3, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 3, 'z': 10, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'load'}
    instructions[155] = {4'd7, 4'd8, 4'd8, 16'd10};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 8, 'z': 8, 'b': 10, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'add'}
    instructions[156] = {4'd1, 4'd2, 4'd4, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 4, 'literal': 0, 'z': 2, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'addl'}
    instructions[157] = {4'd2, 4'd0, 4'd2, 16'd8};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 2, 'b': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'store'}
    instructions[158] = {4'd1, 4'd3, 4'd3, -16'd1};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 3, 'comment': 'pop', 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'literal': -1, 'z': 3, 'op': 'addl'}
    instructions[159] = {4'd5, 4'd8, 4'd3, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27 {'a': 3, 'z': 8, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 27, 'op': 'load'}
    instructions[160] = {4'd10, 4'd0, 4'd0, 16'd162};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 29 {'label': 162, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 29, 'op': 'goto'}
    instructions[161] = {4'd10, 4'd0, 4'd0, 16'd163};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 29 {'label': 163, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 29, 'op': 'goto'}
    instructions[162] = {4'd10, 4'd0, 4'd0, 16'd106};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25 {'label': 106, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 25, 'op': 'goto'}
    instructions[163] = {4'd1, 4'd3, 4'd4, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 23 {'a': 4, 'literal': 0, 'z': 3, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 23, 'op': 'addl'}
    instructions[164] = {4'd1, 4'd4, 4'd7, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 23 {'a': 7, 'literal': 0, 'z': 4, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 23, 'op': 'addl'}
    instructions[165] = {4'd6, 4'd0, 4'd6, 16'd0};///usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 23 {'a': 6, 'trace': /usr/local/lib/python2.7/dist-packages/chips/compiler/include/stdio.h : 23, 'op': 'return'}
  end

  
  always @(posedge clk)
  begin
    load_data <= memory[load_address];
    if(store_enable && state == execute) begin
      memory[store_address] <= store_data;
    end
  end


  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 1 -- FETCH INSTRUCTION
  //                                                                            
  
  always @(posedge clk)
  begin
    //implement memory for instructions
    if (state == instruction_fetch || state == operand_fetch || state == execute) begin
      instruction <= instructions[program_counter];
      program_counter_1 <= program_counter;
    end
  end

  assign opcode    = instruction[27:24];
  assign address_z = instruction[23:20];
  assign address_a = instruction[19:16];
  assign address_b = instruction[3:0];
  assign literal   = instruction[15:0];

  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 2 -- FETCH OPERANDS
  //                                                                            
  
  always @(posedge clk)
  begin
    if (write_enable) begin
      registers[address_z_3] <= result;
    end
    if (state == operand_fetch || state == execute) begin
      opcode_2 <= opcode;
      literal_2 <= literal;
      address_a_2 <= address_a;
      address_b_2 <= address_b;
      address_z_2 <= address_z;
      program_counter_2 <= program_counter_1;
    end
  end
  assign register_a = registers[address_a_2];
  assign register_b = registers[address_b_2];
  assign operand_a = (address_a_2 == address_z_3 && write_enable)?result:register_a;
  assign operand_b = (address_b_2 == address_z_3 && write_enable)?result:register_b;
  assign store_address = operand_a;
  assign load_address = operand_a;
  assign store_data = operand_b;
  assign store_enable = (opcode_2==2);

  //////////////////////////////////////////////////////////////////////////////
  // PIPELINE STAGE 3 -- EXECUTE
  //                                                                            
  
  always @(posedge clk)
  begin

  write_enable <= 0;
  timer_clock <= timer_clock + 1;
  case(state)

    //instruction_fetch
    instruction_fetch: begin
      program_counter <= program_counter + 1;
      state <= operand_fetch;
    end
    //operand_fetch
    operand_fetch: begin
      program_counter <= program_counter + 1;
      state <= execute;
    end
    //execute
    execute: begin
      program_counter <= program_counter + 1;
      address_z_3 <= address_z_2;
      case(opcode_2)

        //literal
        16'd0:
        begin
          result<=$signed(literal_2);
          write_enable <= 1;
        end

        //addl
        16'd1:
        begin
          result<=operand_a + literal_2;
          write_enable <= 1;
        end

        //store
        16'd2:
        begin
        end

        //call
        16'd3:
        begin
          result <= program_counter_2 + 1;
          write_enable <= 1;
          program_counter <= literal_2;
          state <= instruction_fetch;
        end

        //stop
        16'd4:
        begin
        state <= stop;
        end

        //load
        16'd5:
        begin
          state <= load;
        end

        //return
        16'd6:
        begin
          program_counter <= operand_a;
          state <= instruction_fetch;
        end

        //add
        16'd7:
        begin
          long_result = operand_a + operand_b;
          result <= long_result[31:0];
          carry[0] <= long_result[32];
          write_enable <= 1;
        end

        //jmp_if_false
        16'd8:
        begin
          if (operand_a == 0) begin
            program_counter <= literal_2;
            state <= instruction_fetch;
          end
        end

        //write
        16'd9:
        begin
          state <= write;
          write_output <= operand_a;
          write_value <= operand_b;
        end

        //goto
        16'd10:
        begin
          program_counter <= literal_2;
          state <= instruction_fetch;
        end

      endcase

    end

    write:
    begin
      case(write_output)
      0:
      begin
        s_output_rs232_tx_stb <= 1;
        s_output_rs232_tx <= write_value;
        if (output_rs232_tx_ack && s_output_rs232_tx_stb) begin
          s_output_rs232_tx_stb <= 0;
          state <= execute;
        end
      end
      endcase
    end

    load:
    begin
        result <= load_data;
        write_enable <= 1;
        state <= execute;
    end

    wait_state:
    begin
      if (timer) begin
        timer <= timer - 1;
      end else begin
        state <= execute;
      end
    end

    stop:
    begin
    end

    endcase

    if (rst == 1'b1) begin
      timer <= 0;
      timer_clock <= 0;
      program_counter <= 0;
      address_z_3 <= 0;
      result <= 0;
      a = 0;
      b = 0;
      z = 0;
      state <= instruction_fetch;
      s_output_rs232_tx_stb <= 0;
    end
  end
  assign output_rs232_tx_stb = s_output_rs232_tx_stb;
  assign output_rs232_tx = s_output_rs232_tx;

endmodule
